### ISSUE TITLE
unable to reach metadata_service after using docker compose

### ISSUE THREAD

**Issue by ferras** [Netflix/metaflow-service#5]
Description of steps by @aleade
```
I cloned the most recent git repo
I did docker pull netflixoss/metaflow_metadata_service
I changed the docker-compose file only to change the image and the volumes path (last line)
version: "3"
services:
metadata:
  image: "netflixoss/metaflow_metadata_service"
  container_name: "metadata_service"
  ports:
    - "${MF_METADATA_PORT:-5004}:${MF_METADATA_PORT:-5004}"
  volumes:
    - ./metadata_service:/code
I did docker-compose up -d
I did docker exec -it metadata_service /bin/bash
I did curl localhost:8080/ping
```

**Comment by ferras** [comment]
the latest image hasn't been deployed to netflixoss/metaflow_metadata_service on dockerhub so you would need to set the ports to 8080
either via the env variable `MF_METADATA_PORT` or by changing the default in the docker-compose file to 8080.

We will attempt to push the latest build to dockerhub by the end of the week.

you can also build the latest image locally via the following command:
`docker build -t metadata_service .`

**Comment by aleade** [comment]
Hi, 

I changed my docker-compose file into:
```
version: "3"
services:
  metadata:
    image: "metadata_service"
    # image: "netflixoss/metaflow_metadata_service"
    container_name: "metadata_service"
    ports:
      - "${MF_METADATA_PORT:-8080}:${MF_METADATA_PORT:-8080}"
    volumes:
      - ./metadata_service:/code
    environment:
      - MF_METADATA_DB_HOST=db
      - MF_METADATA_DB_PORT=5432
      - MF_METADATA_DB_USER=postgres
      - MF_METADATA_DB_PSWD=postgres
      - MF_METADATA_DB_NAME=postgres
      - MF_METADATA_PORT=${MF_METADATA_PORT:-8080}
      - MF_METADATA_HOST=${MF_METADATA_HOST:-0.0.0.0}
    links:
      - db
  db:
    image: "postgres:11"
    restart: always
    container_name: "my_postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data2
volumes:
  my_dbdata:
```

I built the image using `docker` build -f Dockerfile ./ -t metadata_service`

Bu I am still unable to use `metadata('http://0.0.0.0:8080/metadata_service')` or `metadata('http://172.17.0.1:8080/metadata_service')` (after curling accordingly)

This is the error that I get:
```
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
~/software/anaconda2/envs/metaflow/lib/python3.7/site-packages/metaflow/metadata/service.py in compute_info(cls, val)
     30             resp = requests.get(os.path.join(v, 'ping'), headers=METADATA_SERVICE_HEADERS)
---> 31             resp.raise_for_status()
     32         except:  # noqa E722

~/software/anaconda2/envs/metaflow/lib/python3.7/site-packages/requests/models.py in raise_for_status(self)
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 

HTTPError: 404 Client Error: Not Found for url: http://0.0.0.0:8080/metadata_service/ping

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-10-8df3d891fbd2> in <module>
----> 1 metadata('http://0.0.0.0:8080/metadata_service')

~/software/anaconda2/envs/metaflow/lib/python3.7/site-packages/metaflow/client/core.py in metadata(ms)
     79             return get_metadata()
     80         current_metadata = res[0]
---> 81         current_metadata.INFO = ms
     82     return get_metadata()
     83 

~/software/anaconda2/envs/metaflow/lib/python3.7/site-packages/metaflow/metadata/metadata.py in _set_info(classobject, val)
     26 
     27     def _set_info(classobject, val):
---> 28         v = classobject.compute_info(val)
     29         classobject._INFO = v
     30 

~/software/anaconda2/envs/metaflow/lib/python3.7/site-packages/metaflow/metadata/service.py in compute_info(cls, val)
     31             resp.raise_for_status()
     32         except:  # noqa E722
---> 33             raise ValueError('Metaflow service [%s] unreachable.' % v)
     34         return v
     35 

ValueError: Metaflow service [http://0.0.0.0:8080/metadata_service] unreachable.
```

While if I do `metadata('http://0.0.0.0:8080/')` in my notebook I get: `service@http://0.0.0.0:8080` (no error), but that doesn't seem to work in my flow: `ERROR:root:Authorisation response: 404`
